### ISSUE TITLE
6_Übungsaufgaben Modul 1

### ISSUE THREAD

**Issue by Stekal89** [Stekal89/VB_Exercises#16]
### Modul1 Übungen:

- [x] Create Solution for Modul_01

- [x] Create Project for 6_Uebungsaufgaben

1.
- [x] Erstellen Sie die Methode UpDownString mit der Signatur:
 static string UpDownString(string text)
Die Methode soll im string text abwechselnd ein Wort groß und das nächste Wort klein schrei
ben.
Danach soll sie den text zurückgeben.

2. 
- [x] Erstellen Sie folgendes Benutzermenü.
- a. Benutzer anlegen.
- b. Benutzer löschen.
- c. Benutzer ändern.
- d. Programmende.

- [ ] Legen Sie eine Liste von strings an.
- a. Wenn der Punkt Benutzer anlegen aufgerufen wird, tragen Sie einen neuen String
am Ende in ihre Liste ein.
- b. Wenn der Punkt Benutzer löschen aufgerufen wird, kann ein Benutzer
ausgewählt werden, der danach gelöscht wird.
- c. Benutzer ändern erlaubt erneut die Auswahl eines Benutzers, der danach
geändert werden kann. (neuer name)
- d. Programmende beendet das Programm.

3. 
- [x] Erstellen Sie die Methoden mit den folgenden Signaturen:
 static int CountWords(string sentence)
 static int CountSimilarWords(string sentence, string sentenceToCompare)
 static int CountSimilarSentences(string text, string text2)
CountWords ist eine einfache Hilfsmethode, die sie später benötigen. Sie zählt lediglich die W
örter eines Satzes und gibt deren Anzahl zurück.
CountSimilarWords nimmt zwei Sätze entgegen und zählt wieviele Wörter des ersten Satzes i
m zweiten Satz vorkommen. Verwenden Sie hierzu Schleifen und die Contains Methode.
CountSimilarSentences zählt wieviele Sätze in zwei Texten gleich waren.
Hinweis: Zwei Sätze sind gleich, wenn all ihre Wörter gleich sind. Verwenden Sie dazu Count
SimilarWords und CountWords.

**Comment by Stekal89** [comment]
Finished all exercises, close the ticket.
