### ISSUE TITLE
2_Verzweigungen

### ISSUE THREAD

**Issue by Stekal89** [Stekal89/VB_Exercises#2]
### Aufgabenblatt – Verzweigungen:

- [x] **Create Project for exercises "Aufgabenblatt – Verzweigungen"**

1. 
- [x] Erstellen Sie eine Programm, das eine Integer Variable anlegt. Weisen Sie dieser Integer Variable
den Wert 42 zu. Erstellen Sie eine Verzweigung, die prüft, ob diese Integer Variable einen Wert
hat, der kleiner oder gleich 42 ist. Geben Sie "Kleinergleich 42" auf der Konsole aus, wenn die
Verzweigung betreten wird.

2. 
- [x] Erstellen Sie ein Programm, das eine Zeichenkette von der Konsole einliest. Erstellen Sie eine
Verzweigung die prüft, ob der eingegebene Name ihrem Namen entspricht. Geben Sie "Hallo,
'Name'" aus, wenn ja. Ansonsten geben Sie "Geh weg, ich kenne dich nicht" aus.

3. 
- [x] Erstellen Sie ein Programm, das eine Ganzzahl einliest. Prüfen Sie, ob die Eingabe kleiner 0 ist.
Geben Sie "Du hast eine negative Zahl eingegeben aus, wenn das zutrifft. Prüfen Sie ob die Zahl
genau null ist. Geben Sie in diesem Fall "Du hast 0 eingegeben" aus. Prüfen Sie weiters, ob die
Zahl größer 0 ist. Geben Sie in diesem Fall: "Du hast eine positive Zahl eingegeben" aus.

4. 
- [x] Erstellen Sie ein Programm, das eine Zahl, das Alter, von der Konsole einliest. Wenn die Zahl
kleiner 3 ist geben Sie Kleinkind aus. Wenn die Zahl kleiner 10 ist geben Sie Kind aus. Wenn die
Zahl kleiner 18 ist geben Sie Jugendlicher aus. Wenn die Zahl kleiner 70 ist geben Sie
Erwachsener aus. Wenn die Zahl größer oder gleich 70 ist geben Sie Pensionist aus.

5. 
- [x] Lesen Sie eine Zeichenkette von der Konsole ein. Prüfen Sie, ob diese Zeichenkette aus 'r'
besteht. Geben Sie in diesem Fall: 'Von der Festplatte lesen' aus. Wenn die eingelesene
Zeichenkette aus 'w' besteht geben Sie "Schreiben" aus. Wenn die Zeichenkette aus 'rw'
besteht, geben Sie "Lesen und Schreiben" aus. Ansonsten geben Sie "Unbekannter Befehl" aus.

6. 
- [x] Erstellen Sie ein Programm (oder eine Methode), das prüft wer im Blackjack gewonnen hat.:
Lesen Sie dazu Werte in zwei Integer Variablen ein, die die Punktestände der Spieler darstellen.
Benutzen Sie folgende Regeln um Herauszufinden wer gewonnen hat und geben Sie das Ergebnis
auf der Konsole aus.:
   - [x] Ein Spieler dessen Zahl größer als 21 ist hat verloren.
   - [x]  Der Spieler der die größere Zahl hat, hat gewonnen.
   - [x]  Haben beide die gleiche Zahl ist das Spiel unentschieden.

7. 
- [x] Erstellen Sie einen primitiven Taschenrechner. Der Benutzer soll eine Rechenart auswählen
können(+,-,/,*) und danach zwei Zahlen eingeben um das Ergebnis zu berechnen.

**Comment by Stekal89** [comment]
Finished all exercises successfully.
