### ISSUE TITLE
3_Schleifen

### ISSUE THREAD

**Issue by Stekal89** [Stekal89/VB_Exercises#3]
### Aufgabenblatt - Schleifen:

- [x] **Create Project for exercises "Aufgabenblatt – Schleifen"**

1. 
- [x] Erstellen Sie eine While Schleife, die die Zahlen von 0 bis 10 ausgibt.

2. 
- [x] Erstellen Sie eine For Schleife, die die Zahlen von 0 bis 100 ausgibt.

3. 
- [x] Erstellen Sie eine While Schleife, die rückwärts von 100 bis - 10 zählt und die Zahlen ausgibt.

4. 
- [x] Erstellen Sie eine While Schleife, die in zweier- Schritten von 0 bis 30 zählt und die Zahlen
ausgibt.

5. 
- [x] Erstellen Sie ein Programm, das zwei Zahlen von 0 bis 10 von der Konsole einliest. Die Schleife
soll von der ersten eingegebenen Zahl bis zur zweiten eingegebenen Zahl zählen.

6. 
- [x] Erstellen Sie ein Programm, das je nach Eingabe eine bestimmte Anzahl von * ausgibt.

7. 
- [x] Erstellen Sie ein Programm, das von 0 bis 100 zählt. Das Programm soll bei jeder Zahl überprüfen,
ob Sie ohne Rest durch 2 Teilbar ist. (Hinweis: Modulo. zahl Mod 2 = 0). Wenn ja, soll das
Programm 'Zahl' ist durch 2 Teilbar ausgeben. ansonsten 'Zahl' ist nicht durch 2 Teilbar.

8. 
- [x] Verbessern Sie das Programm aus Übung 7. Der Benutzer kann jetzt einen Zahlenbereich wählen
und eine Zahl. Danach soll überprüft werden welche Zahlen in dem Zahlenbereich durch die Zahl
teilbar sind.

9. 
- [x] Entwickeln Sie ein Programm, dass einem Einbrecher hilft ein 4 Stelliges Zahlenschloss zu
knacken. Das Zahlenschloss akzeptiert an jeder Stelle Zahlen von 0-36. Es besitzt 4 Stellen.
Eine mögliche Kombination wäre zb.
36-22-11-14
Schreiben Sie eine Funktion, die ihnen alle möglichen Kombinationen des Zahlenschlosses (auf
der Konsole) ausgibt.

10. 
- [x] Erstellen Sie ein Programm, das das kleine Einmaleins ausgibt.

11. 
- [X] Geben Sie einen Christbaum aus. Der Benutzer kann die Höhe wählen:
   zb.: Höhe 10
   Die Formel für den Baum ist:
   Leerzeichenanzahl Links/Rechts = Höhe – 1 – i
   Sterne = i * 2 + 1
   i = Nummer des Durchlaufs.

**Comment by Stekal89** [comment]
Finished all tasks!
