### ISSUE TITLE
4_Zahlenraten

### ISSUE THREAD

**Issue by Stekal89** [Stekal89/VB_Exercises#4]
### Zahlenraten:

- [x] **Create Project for exercises "Zahlenraten"**

**Programmieren Sie ein Spiel, bei dem der Benutzer eine Zufallszahl zwischen 1 und 6 erraten muss.**
   1. 
   - [x] Lesen Sie dazu einen Wert von der Eingabeaufforderung ein.
   2. 
   - [x] Ermitteln Sie danach einen Wert zwischen 1 und 6 mittels der Funktion Random.Next(1,6)
   3. 
   - [x] Wandeln Sie die eingegebene Zeichenkette in eine Zahl um ! (int.Parse(..))
   4. 
   - [x] Vergleichen Sie den eingegebenen Wert mit der eingelesenen Zahl. Sind sie gleich, hat der
       Benutzer gewonnen andernfalls verloren. Geben Sie eine enstprechende Nachricht auf der
       Kommandozeile aus.
   5. 
   - [x] Erweitern Sie ihr Programm, sodass es solange weitermacht, bis der Benutzer ein mal
       gewonnen hat.
   6. 
   - [x] Erweitern Sie ihr Programm, sodass der Benutzer 6 mal gewinnen muss bevor das Spiel
       gewonnen ist.
        Benutzen Sie Console.Clear() an einer geeigneten Stelle um die alten eingaben zu löschen.

**Comment by Stekal89** [comment]
Finished all tasks of this Ticket!
