### ISSUE TITLE
Create Unit tests for Project: "5_Dual-Converter"

### ISSUE THREAD

**Issue by Stekal89** [Stekal89/VB_Exercises#44]
- [x] Create Unit Test Project

- [x] Create Unit Test for Method: "ConvertStringIntoInteger"
- - [x] input is Null, or Empty
  - - [x] Test-Method for Console-Output
  - - [x] Test-Method for Return-Value
- - [x] input is Whitespace
  - - [x] Test-Method for Console-Output
  - - [x] Test-Method for Return-Value
- - [x] input is not an Integer e.g. "bla blubb"
  - - [x] Test-Method for Console-Output
  - - [x] Test-Method for Return-Value
- - [x] valid correct input
  - - [x] Test-Method for Console-Output
  - - [x] Test-Method for Return-Value

- [x] Create Unit Test for Method: "GetRestOfIntegerInStack"
- - [x] Only with valid correct input -> Test-Method for Return-Value
  - - [x] Test for Binary Return-Value
  - - [x] Test for Octa Return-Value
  - - [x] Test for HEX Return-Value

- [x] Create Unit Test for Method: "OrderAndGroupRestResult"
- - [x] Only with valid correct input -> Test-Method for Return-Value
  - - [x] Test for Binary Return-Value
  - - [x] Test for Octa Return-Value
  - - [x] Test for HEX Return-Value

- [x] Create Unit Test for Method: "GetBinarayResult"
- - [x] input is NULL
  - - [x] Test-Method for Console-Output
  - - [x] Test-Method for Return-Value
- - [x] valid correct input
  - - [x] Test-Method for Console-Output 
  - - [x] Test-Method for Return-Value

- [x] Create Unit Test for Method: "GetOctaResult"
- - [x] input is NULL
  - - [x] Test-Method for Console-Output 
  - - [x] Test-Method for Return-Value
- - [x] valid correct input 
  - - [x] Test-Method for Console-Output 
  - - [x] Test-Method for Return-Value

- [x] Create Unit Test for Method: "GetHEXResult"
- - [x] input is NULL
  - - [x] Test-Method for Console-Output 
  - - [x] Test-Method for Return-Value
- - [x] valid correct input
  - - [x] Test-Method for Console-Output 
  - - [x] Test-Method for Return-Value

**Comment by Stekal89** [comment]
Finished all tasks, all necessary testcases are created.
Close the Ticket.
